export const Plan = {
  free: {
    name: "Free Trial",
    price: 0,
    aiCredits: 20,
    validDays: 7,
    emailAi: false,
    landingPageAi: false,
    replySequenceAi: false,
    landingPages: 1,
    teamMembers: 1,
    customDomains: false,
    prioritySupport: false,
    dailyLimit: 10,
  },

  starter: {
    name: "Starter",
    price: 10,
    aiCredits: 200,
    validDays: 30,
    emailAi: true,
    landingPageAi: "basic",
    replySequenceAi: false,
    landingPages: 3,
    teamMembers: 3,
    customDomains: true,
    prioritySupport: false,
    dailyLimit: 50,
  },

  pro: {
    name: "Pro",
    price: 29,
    aiCredits: 3000,
    validDays: 30,
    emailAi: true,
    landingPageAi: "advanced",
    replySequenceAi: true,
    landingPages: 10,
    teamMembers: 10,
    customDomains: true,
    prioritySupport: true,
    dailyLimit: 200,
  },

  agency: {
    name: "Agency",
    price: 99,
    aiCredits: 14000,
    validDays: 30,
    emailAi: true,
    landingPageAi: "full",
    replySequenceAi: true,
    landingPages: "unlimited",
    teamMembers: "unlimited",
    customDomains: true,
    prioritySupport: true,
    dailyLimit: "unlimited",
  },
};
